version: "3.9"
# Usage : docker compose -f docker-compose.yaml -f docker-compose.prod.yml up -d

services:

  back:
    build:
      target: prod
    environment:
      APP_ENV:   prod
      APP_DEBUG: "0"
      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: "0.1"   # 10% des traces en prod
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512M

  front:
    build:
      target: prod
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M

  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.enable-lifecycle
      - --web.enable-admin-api

  tempo:
    environment:
      TEMPO_STORAGE_TRACE_BACKEND: s3   # Passer à S3 en prod (à configurer)
