version: "3.9"
# Chargé automatiquement en développement

services:

  back:
    build:
      target: dev
    environment:
      APP_ENV:      dev
      APP_DEBUG:    "1"
      XDEBUG_MODE:  debug
      OTEL_TRACES_SAMPLER: always_on   # tracer 100% des requêtes en dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  front:
    build:
      target: dev
    environment:
      NODE_ENV: development

  # Capture e-mails en dev
  mail:
    image: axllent/mailpit:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mail
    restart: unless-stopped
    ports:
      - "${MAIL_MYAPP_SMTP_PORT}:1025"
      - "${MAIL_MYAPP_UI_PORT}:8025"
    networks:
      - backend
