log.console       = true
log.console.level = info
heartbeat         = 60
channel_max       = 2047
vm_memory_high_watermark.relative = 0.4
disk_free_limit.absolute          = 50MB
# Activer le plugin Prometheus
prometheus.return_per_object_metrics = true
